//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;

namespace Smart.Sample.Core.Entites
{
    /// <summary>
    /// 系统支持 角色 实体类
    /// </summary>
    [Serializable]
	public partial class Role
	{
         /// <summary>
         /// 获取或设置 角色ID
         /// </summary>
		public virtual int RoleId { get; set; }
         /// <summary>
         /// 获取或设置 门店ID
         /// </summary>
		public virtual int? BeautySalonId { get; set; }
         /// <summary>
         /// 获取或设置 角色名称
         /// </summary>
		public virtual string Name { get; set; }
         /// <summary>
         /// 获取或设置 角色说明
         /// </summary>
		public virtual string Note { get; set; }
         /// <summary>
         /// 获取或设置 是否是系统角色
         /// </summary>
		public virtual bool IsSysRole { get; set; }
         /// <summary>
         /// 获取或设置 上次更新人
         /// </summary>
		public virtual int? UpdateUserId { get; set; }
         /// <summary>
         /// 获取或设置 创建时间
         /// </summary>
		public virtual DateTime CreateTime { get; set; }
         /// <summary>
         /// 获取或设置 创建人
         /// </summary>
		public virtual int CreateUserId { get; set; }
         /// <summary>
         /// 获取或设置 更新时间
         /// </summary>
		public virtual DateTime? UpdateTime { get; set; }
	}
    /// <summary>
    /// 系统支持 角色权限关联 实体类
    /// </summary>
    [Serializable]
	public partial class RoleSysAction
	{
         /// <summary>
         /// 获取或设置 
         /// </summary>
		public virtual int RoleSysActionId { get; set; }
         /// <summary>
         /// 获取或设置 角色ID
         /// </summary>
		public virtual int RoleId { get; set; }
         /// <summary>
         /// 获取或设置 操作权限ID
         /// </summary>
		public virtual string SysActionId { get; set; }
         /// <summary>
         /// 获取或设置 创建时间
         /// </summary>
		public virtual DateTime CreateTime { get; set; }
         /// <summary>
         /// 获取或设置 创建人
         /// </summary>
		public virtual int CreateUserId { get; set; }
	}
    /// <summary>
    /// 系统支持 操作权限 实体类
    /// </summary>
    [Serializable]
	public partial class SysAction
	{
         /// <summary>
         /// 获取或设置 
         /// </summary>
		public virtual string SysActionId { get; set; }
         /// <summary>
         /// 获取或设置 操作名称
         /// </summary>
		public virtual string Name { get; set; }
         /// <summary>
         /// 获取或设置 功能Id
         /// </summary>
		public virtual string SysFuncId { get; set; }
         /// <summary>
         /// 获取或设置 操作说明
         /// </summary>
		public virtual string Remark { get; set; }
	}
    /// <summary>
    /// 系统支持 系统功能 实体类
    /// </summary>
    [Serializable]
	public partial class SysFunc
	{
         /// <summary>
         /// 获取或设置 功能编码
         /// </summary>
		public virtual string SysFuncId { get; set; }
         /// <summary>
         /// 获取或设置 功能名称
         /// </summary>
		public virtual string Name { get; set; }
         /// <summary>
         /// 获取或设置 功能地址
         /// </summary>
		public virtual string Url { get; set; }
         /// <summary>
         /// 获取或设置 上级功能编码
         /// </summary>
		public virtual string ParentId { get; set; }
         /// <summary>
         /// 获取或设置 显示顺序
         /// </summary>
		public virtual int DisplayIndex { get; set; }
         /// <summary>
         /// 获取或设置 显示图标
         /// </summary>
		public virtual string Icon { get; set; }
         /// <summary>
         /// 获取或设置 功能说明
         /// </summary>
		public virtual string Remark { get; set; }
	}
    /// <summary>
    /// 系统支持 系统用户 实体类
    /// </summary>
    [Serializable]
	public partial class SysUser
	{
         /// <summary>
         /// 获取或设置 系统用户ID
         /// </summary>
		public virtual int SysUserId { get; set; }
         /// <summary>
         /// 获取或设置 门店ID
         /// </summary>
		public virtual int BeautySalonId { get; set; }
         /// <summary>
         /// 获取或设置 员工ID
         /// </summary>
		public virtual int? EmployeeId { get; set; }
         /// <summary>
         /// 获取或设置 用户名
         /// </summary>
		public virtual string UserName { get; set; }
         /// <summary>
         /// 获取或设置 登录名称
         /// </summary>
		public virtual string LoginName { get; set; }
         /// <summary>
         /// 获取或设置 登录密码
         /// </summary>
		public virtual string Password { get; set; }
         /// <summary>
         /// 获取或设置 是否是超级管理 员
         /// </summary>
		public virtual bool IsAdmin { get; set; }
         /// <summary>
         /// 获取或设置 删除标志
         /// </summary>
		public virtual bool IsDelete { get; set; }
         /// <summary>
         /// 获取或设置 最后一次登录时间
         /// </summary>
		public virtual DateTime? LastLoginTime { get; set; }
         /// <summary>
         /// 获取或设置 创建时间
         /// </summary>
		public virtual DateTime CreateTime { get; set; }
         /// <summary>
         /// 获取或设置 创建人
         /// </summary>
		public virtual int CreateUserId { get; set; }
         /// <summary>
         /// 获取或设置 修改时间
         /// </summary>
		public virtual DateTime? UpdateTime { get; set; }
         /// <summary>
         /// 获取或设置 修改人
         /// </summary>
		public virtual int? UpdateUserId { get; set; }
	}
    /// <summary>
    /// 系统支持 用户角色 实体类
    /// </summary>
    [Serializable]
	public partial class UserRole
	{
         /// <summary>
         /// 获取或设置 
         /// </summary>
		public virtual int UserRoleId { get; set; }
         /// <summary>
         /// 获取或设置 
         /// </summary>
		public virtual int UserId { get; set; }
         /// <summary>
         /// 获取或设置 
         /// </summary>
		public virtual int RoleId { get; set; }
         /// <summary>
         /// 获取或设置 
         /// </summary>
		public virtual DateTime CreateTime { get; set; }
         /// <summary>
         /// 获取或设置 
         /// </summary>
		public virtual int CreateUserId { get; set; }
	}
} 
